import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, Bell, Check, ChevronDown, CircleDollarSign, FileText, LayoutDashboard, Menu, Plus, Search, Settings, Sparkles, Users, Wallet, X, Zap } from 'lucide-react';
import './styles.css';

type Status = 'Paid' | 'Pending' | 'Overdue' | 'Draft';
type Invoice = { id:string; client:string; email:string; amount:number; due:string; status:Status; items:string };

const seed: Invoice[] = [
  {id:'INV-1042',client:'Sarah Chen',email:'sarah@northstar.studio',amount:1280,due:'Aug 24, 2026',status:'Pending',items:'Brand identity package'},
  {id:'INV-1041',client:'Marcus Lee',email:'marcus@leecreative.co',amount:850,due:'Aug 18, 2026',status:'Paid',items:'Landing page design'},
  {id:'INV-1040',client:'Apex Media',email:'finance@apexmedia.co',amount:2400,due:'Aug 12, 2026',status:'Overdue',items:'Monthly creative retainer'},
  {id:'INV-1039',client:'Nadia Khan',email:'nadia@brightlabs.io',amount:540,due:'Sep 02, 2026',status:'Draft',items:'3 social media templates'}
];

function App(){
 const [page,setPage]=useState('Overview'); const [menu,setMenu]=useState(false); const [showCreate,setShowCreate]=useState(false); const [showAI,setShowAI]=useState(false); const [query,setQuery]=useState(''); const [toast,setToast]=useState('');
 const [invoices,setInvoices]=useState<Invoice[]>(()=>{try{return JSON.parse(localStorage.getItem('invoicepilot_invoices')||'null')||seed}catch{return seed}});
 const filtered=useMemo(()=>invoices.filter(i=>(i.client+i.id+i.status).toLowerCase().includes(query.toLowerCase())),[invoices,query]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2600)};
 const addInvoice=(invoice:Invoice)=>{const next=[invoice,...invoices];setInvoices(next);localStorage.setItem('invoicepilot_invoices',JSON.stringify(next));setShowCreate(false);notify('Invoice created successfully');};
 return <div className="app">
  <aside className={menu?'sidebar open':'sidebar'}>
   <div className="brand"><div className="brand-mark"><Zap size={18} fill="currentColor"/></div><span>InvoicePilot</span></div>
   <div className="workspace"><div className="avatar">ZR</div><div><strong>Zarif Rahman</strong><small>Personal workspace</small></div><ChevronDown size={15}/></div>
   <nav>
    <Nav icon={<LayoutDashboard/>} label="Overview" active={page==='Overview'} onClick={()=>setPage('Overview')}/>
    <Nav icon={<FileText/>} label="Invoices" active={page==='Invoices'} badge={invoices.length} onClick={()=>setPage('Invoices')}/>
    <Nav icon={<Users/>} label="Clients" active={page==='Clients'} onClick={()=>setPage('Clients')}/>
    <Nav icon={<Wallet/>} label="Payments" active={page==='Payments'} onClick={()=>setPage('Payments')}/>
    <Nav icon={<CircleDollarSign/>} label="Analytics" active={page==='Analytics'} onClick={()=>setPage('Analytics')}/>
   </nav>
   <div className="ai-card"><div className="ai-icon"><Sparkles size={16}/></div><strong>AI Invoice</strong><p>Turn a sentence into a ready-to-send invoice.</p><button onClick={()=>setShowAI(true)}>Try it <ArrowUpRight size={14}/></button></div>
   <div className="sidebar-bottom"><Nav icon={<Settings/>} label="Settings" active={page==='Settings'} onClick={()=>setPage('Settings')}/><div className="plan"><div><small>FREE PLAN</small><strong>5 of 5 invoices</strong></div><button onClick={()=>notify('Upgrade flow coming next')}>Upgrade</button></div></div>
  </aside>
  <main className="main">
   <header className="topbar"><button className="mobile-menu" onClick={()=>setMenu(!menu)}><Menu/></button><div className="breadcrumbs"><span>Workspace</span><b>/</b><strong>{page}</strong></div><div className="top-actions"><button className="icon-btn"><Bell size={18}/><i/></button><button className="profile">ZR</button></div></header>
   {page==='Overview'&&<Overview invoices={invoices} onCreate={()=>setShowCreate(true)} onAI={()=>setShowAI(true)} onPage={setPage} onNotify={notify}/>} 
   {page==='Invoices'&&<Invoices invoices={filtered} query={query} setQuery={setQuery} onCreate={()=>setShowCreate(true)} onNotify={notify}/>} 
   {page==='Clients'&&<Clients invoices={invoices} onCreate={()=>setShowCreate(true)}/>} 
   {page==='Payments'&&<Payments invoices={invoices}/>} 
   {page==='Analytics'&&<Analytics invoices={invoices}/>} 
   {page==='Settings'&&<SettingsPage onNotify={notify}/>} 
  </main>
  {showCreate&&<CreateModal onClose={()=>setShowCreate(false)} onSave={addInvoice}/>} 
  {showAI&&<AIModal onClose={()=>setShowAI(false)} onSave={addInvoice}/>} 
  {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}
function Nav({icon,label,active,badge,onClick}:{icon:React.ReactNode;label:string;active:boolean;badge?:number;onClick:()=>void}){return <button className={active?'nav active':'nav'} onClick={onClick}>{icon}<span>{label}</span>{badge!==undefined&&<em>{badge}</em>}</button>}
function Overview({invoices,onCreate,onAI,onPage,onNotify}:{invoices:Invoice[];onCreate:()=>void;onAI:()=>void;onPage:(p:string)=>void;onNotify:(s:string)=>void}){
 const paid=invoices.filter(x=>x.status==='Paid').reduce((a,b)=>a+b.amount,0); const pending=invoices.filter(x=>x.status==='Pending').reduce((a,b)=>a+b.amount,0); const overdue=invoices.filter(x=>x.status==='Overdue').reduce((a,b)=>a+b.amount,0);
 return <section className="content"><div className="hero-row"><div><p className="eyebrow">WEDNESDAY, AUGUST 19</p><h1>Good evening, Zarif <span>👋</span></h1><p className="muted">Here's what is happening with your invoices.</p></div><div className="hero-actions"><button className="secondary" onClick={onAI}><Sparkles size={16}/> AI create</button><button className="primary" onClick={onCreate}><Plus size={17}/> New invoice</button></div></div>
  <div className="stat-grid"><Stat title="Collected" value={'$'+paid.toLocaleString()} change="+12.8%" icon={<CircleDollarSign/>}/><Stat title="Outstanding" value={'$'+pending.toLocaleString()} change="3 invoices" icon={<Wallet/>}/><Stat title="Overdue" value={'$'+overdue.toLocaleString()} change="Needs attention" danger icon={<Bell/>}/><Stat title="Collection rate" value="86.4%" change="+4.2%" icon={<Zap/>}/></div>
  <div className="section-grid"><div className="panel chart-panel"><div className="panel-head"><div><h2>Revenue</h2><p>Collected revenue over the last 6 months</p></div><select><option>Last 6 months</option><option>This year</option></select></div><div className="chart"><div className="y"><span>$8k</span><span>$6k</span><span>$4k</span><span>$2k</span><span>$0</span></div><div className="bars">{[46,62,52,74,68,91].map((h,i)=><div className="bar-wrap" key={i}><div className="bar" style={{height:h+'%'}}/><small>{['Mar','Apr','May','Jun','Jul','Aug'][i]}</small></div>)}</div></div></div>
   <div className="panel activity"><div className="panel-head"><div><h2>Quick actions</h2><p>Jump back into your workflow</p></div></div><button onClick={onCreate} className="action-row"><span className="action-icon"><Plus/></span><div><strong>Create an invoice</strong><small>Build a polished invoice from scratch</small></div><ArrowUpRight/></button><button onClick={onAI} className="action-row"><span className="action-icon ai"><Sparkles/></span><div><strong>Ask AI to invoice</strong><small>Describe the work in plain English</small></div><ArrowUpRight/></button><button onClick={()=>onPage('Clients')} className="action-row"><span className="action-icon"><Users/></span><div><strong>Add a client</strong><small>Save client details for faster billing</small></div><ArrowUpRight/></button></div></div>
  <div className="panel invoices-panel"><div className="panel-head"><div><h2>Recent invoices</h2><p>Your latest billing activity</p></div><button className="link-btn" onClick={()=>onPage('Invoices')}>View all <ArrowUpRight size={15}/></button></div><InvoiceTable invoices={invoices.slice(0,4)} onNotify={onNotify}/></div>
 </section>
}
function Stat({title,value,change,icon,danger}:{title:string;value:string;change:string;icon:React.ReactNode;danger?:boolean}){return <div className="stat"><div className="stat-top"><span>{title}</span><div className="stat-icon">{icon}</div></div><strong>{value}</strong><small className={danger?'danger':''}>{change}</small></div>}
function InvoiceTable({invoices,onNotify}:{invoices:Invoice[];onNotify:(s:string)=>void}){return <div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Client</th><th>Due</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><strong>{i.id}</strong><small>{i.items}</small></td><td><strong>{i.client}</strong><small>{i.email}</small></td><td>{i.due}</td><td><strong>${i.amount.toLocaleString()}</strong></td><td><StatusBadge status={i.status}/></td><td><button className="dots" onClick={()=>onNotify('Invoice actions coming next')}>•••</button></td></tr>)}</tbody></table></div>}
function StatusBadge({status}:{status:Status}){return <span className={'status '+status.toLowerCase()}><i/>{status}</span>}
function Invoices({invoices,query,setQuery,onCreate,onNotify}:{invoices:Invoice[];query:string;setQuery:(x:string)=>void;onCreate:()=>void;onNotify:(x:string)=>void}){return <section className="content"><div className="page-head"><div><p className="eyebrow">BILLING</p><h1>Invoices</h1><p className="muted">Create, send and track every invoice in one place.</p></div><button className="primary" onClick={onCreate}><Plus size={17}/> New invoice</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search invoices..." value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="filter">All statuses <ChevronDown size={15}/></button></div><div className="panel invoices-panel"><InvoiceTable invoices={invoices} onNotify={onNotify}/></div></section>}
function Clients({invoices,onCreate}:{invoices:Invoice[];onCreate:()=>void}){const names=[...new Set(invoices.map(x=>x.client))];return <section className="content"><div className="page-head"><div><p className="eyebrow">RELATIONSHIPS</p><h1>Clients</h1><p className="muted">Keep every client and their billing history organized.</p></div><button className="primary" onClick={onCreate}><Plus size={17}/> New invoice</button></div><div className="client-grid">{names.map((n,i)=>{const rows=invoices.filter(x=>x.client===n);const total=rows.reduce((a,b)=>a+b.amount,0);return <div className="client-card" key={n}><div className="client-avatar">{n.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><h3>{n}</h3><p>{rows[0].email}</p><div className="client-total"><span>Total billed</span><strong>${total.toLocaleString()}</strong></div><button className="outline">View client <ArrowUpRight size={14}/></button></div>})}</div></section>}
function Payments({invoices}:{invoices:Invoice[]}){return <section className="content"><div className="page-head"><div><p className="eyebrow">CASH FLOW</p><h1>Payments</h1><p className="muted">A clear view of money collected and still due.</p></div></div><div className="stat-grid"><Stat title="Collected" value={'$'+invoices.filter(x=>x.status==='Paid').reduce((a,b)=>a+b.amount,0).toLocaleString()} change="All time" icon={<CircleDollarSign/>}/><Stat title="Awaiting payment" value={'$'+invoices.filter(x=>x.status!=='Paid').reduce((a,b)=>a+b.amount,0).toLocaleString()} change="Open balance" icon={<Wallet/>}/></div><div className="panel invoices-panel"><InvoiceTable invoices={invoices.filter(x=>x.status!=='Draft')} onNotify={()=>{}}/></div></section>}
function Analytics({invoices}:{invoices:Invoice[]}){const total=invoices.reduce((a,b)=>a+b.amount,0);return <section className="content"><div className="page-head"><div><p className="eyebrow">INSIGHTS</p><h1>Analytics</h1><p className="muted">Understand your billing performance at a glance.</p></div></div><div className="stat-grid"><Stat title="Gross billed" value={'$'+total.toLocaleString()} change="Across all invoices" icon={<CircleDollarSign/>}/><Stat title="Average invoice" value={'$'+Math.round(total/Math.max(invoices.length,1)).toLocaleString()} change="Per invoice" icon={<FileText/>}/><Stat title="Invoices" value={String(invoices.length)} change="Total created" icon={<FileText/>}/><Stat title="Paid rate" value={Math.round(invoices.filter(x=>x.status==='Paid').length/Math.max(invoices.length,1)*100)+'%'} change="By invoice count" icon={<Check/>}/></div><div className="panel insight"><h2>What needs your attention</h2><p>There are <strong>{invoices.filter(x=>x.status==='Overdue').length} overdue invoices</strong>. Following up today could unlock <strong>${invoices.filter(x=>x.status==='Overdue').reduce((a,b)=>a+b.amount,0).toLocaleString()}</strong> in cash flow.</p></div></section>}
function SettingsPage({onNotify}:{onNotify:(s:string)=>void}){return <section className="content"><div className="page-head"><div><p className="eyebrow">WORKSPACE</p><h1>Settings</h1><p className="muted">Customize how InvoicePilot works for you.</p></div></div><div className="settings-grid"><div className="panel form-panel"><h2>Business profile</h2><p>Your information appears on invoices.</p><label>Business name<input defaultValue="Zarif Creative"/></label><label>Business email<input defaultValue="hello@zarifcreative.com"/></label><label>Default currency<select defaultValue="USD"><option>USD — US Dollar</option><option>BDT — Bangladeshi Taka</option><option>EUR — Euro</option></select></label><button className="primary" onClick={()=>onNotify('Settings saved')}>Save changes</button></div><div className="panel form-panel"><h2>Invoice defaults</h2><p>Set smart defaults to save time.</p><label>Invoice prefix<input defaultValue="INV-"/></label><label>Payment terms<select defaultValue="15"><option value="7">Due in 7 days</option><option value="15">Due in 15 days</option><option value="30">Due in 30 days</option></select></label><label>Default tax<input defaultValue="0"/></label></div></div></section>}
function CreateModal({onClose,onSave}:{onClose:()=>void;onSave:(i:Invoice)=>void}){const [client,setClient]=useState('');const [email,setEmail]=useState('');const [amount,setAmount]=useState('');const [items,setItems]=useState('');return <Modal title="Create invoice" subtitle="A clean invoice in under a minute." onClose={onClose}><div className="modal-form"><label>Client name<input autoFocus value={client} onChange={e=>setClient(e.target.value)} placeholder="e.g. Sarah Chen"/></label><label>Client email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="sarah@company.com"/></label><label>What are you billing for?<input value={items} onChange={e=>setItems(e.target.value)} placeholder="e.g. Brand identity package"/></label><label>Amount<input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></label><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!client||!amount} onClick={()=>onSave({id:'INV-'+(1043+Math.floor(Math.random()*100)),client,email,amount:Number(amount),due:'Sep 03, 2026',status:'Pending',items:items||'Professional services'})}>Create invoice <ArrowUpRight size={15}/></button></div></div></Modal>}
function AIModal({onClose,onSave}:{onClose:()=>void;onSave:(i:Invoice)=>void}){const [text,setText]=useState('');const [generated,setGenerated]=useState(false);return <Modal title="AI invoice" subtitle="Describe the work naturally. Review before anything is saved." onClose={onClose}><div className="ai-modal"><div className="ai-prompt"><Sparkles size={18}/><textarea autoFocus value={text} onChange={e=>{setText(e.target.value);setGenerated(false)}} placeholder={'Try: “Invoice Sarah Chen $1,280 for a brand identity package, due next Friday.”'}/></div>{generated&&<div className="generated"><div><span>CLIENT</span><strong>Sarah Chen</strong></div><div><span>WORK</span><strong>Brand identity package</strong></div><div><span>TOTAL</span><strong>$1,280</strong></div></div>}<button className="primary full" disabled={!text} onClick={()=>setGenerated(true)}>{generated?'Generate again':'Generate invoice'} <Sparkles size={15}/></button>{generated&&<button className="secondary full" onClick={()=>onSave({id:'INV-'+(1043+Math.floor(Math.random()*100)),client:'Sarah Chen',email:'',amount:1280,due:'Sep 03, 2026',status:'Pending',items:'Brand identity package'})}>Save invoice <Check size={15}/></button>}<p className="fine">AI suggestions are editable. InvoicePilot never sends an invoice without your confirmation.</p></div></Modal>}
function Modal({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button onClick={onClose} className="close"><X size={18}/></button></div>{children}</div></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
